### ISSUE TITLE
Achievements calculation

### ISSUE THREAD

**Issue by tchx84** [Arxcis/flatstat#16]
Looking at the achievements list, I see Steam at the top, are these stars?

![image](https://user-images.githubusercontent.com/481418/99855147-e98d2f00-2b64-11eb-989d-197d8dc9f7ab.png)

**Comment by Arxcis** [comment]
- They are Github Stars. 
- The icons are UTF-characters (emojis) so they look different on different platforms. 
- It is just the apps sorted by Github Stars.
<img src="https://user-images.githubusercontent.com/3092618/99856244-d5f3bf80-2b88-11eb-9f83-a7ae926b1b54.png" width=600>

**Comment by Arxcis** [comment]
I can see why this is confusing now :sweat_smile: It was simpler before when the section was named `stars` instead of `apps`, so I think I am going back to that.

**Comment by tchx84** [comment]
Yeah, this is looking great btw :)

**Comment by Arxcis** [comment]
Thank you for your support :pray:

**Comment by Arxcis** [comment]
Also @tchx84, I think I am using `portals`  in the wrong way. I think none of the `--talk-names`  are actual `portals`. The actual `org.freedesktop.portal.*` are not listed in the `.yaml|.json`-files.

I don't think there is any way to detect which `org.freedesktop.portal.*` an app is using, before running it. After you are running the application, you may dynamically check the permissions-store, which your app `Flatseal`  is able to do soon :1st_place_medal: :+1: :clap: 

>Flatpak grants sandboxed applications talk access to names in the org.freedesktop.portal.* prefix. One possible way to use the portal APIs is thus just to make D-Bus calls. For many of the portals, toolkits (e.g. GTK+) are expected to support portals transparently if you use suitable high-level APIs.
https://github.com/flatpak/xdg-desktop-portal#using-portals

It is transparent to us, which is ok. I am just sayin'.

Having said that, I think I will rename the use of the words `portals`  --> `talk-names`

**Comment by tchx84** [comment]
> Also @tchx84, I think I am using `portals` in the wrong way. I think none of the `--talk-names` are actual `portals`. The actual `org.freedesktop.portal.*` are not listed in the `.yaml|.json`-files, right?
> 
> I don't think there is any way to detect which `org.freedesktop.portal.*` an app is using, before running it. After you are running the application, you may dynamically check the permissions-store, which your app `Flatseal` is able to do soon

Yes, I was going to mention that in another issue, but yes these are not portals. These are other holes, basically the app is talking to system/session services through DBus.

The tricky thing is, you can't tell if the app is using portals without looking at the actual code. So my suggestion would be to remove that list and account these as holes.

**Comment by Arxcis** [comment]
> The tricky thing is, you can't tell if the app is using portals without looking at the actual code. So my suggestion would be to remove that list and account these as holes.

I think I am going to keep the list, but rename it to `talk-names` for now. But yes, I will have to define some new holes as well.

**Comment by Arxcis** [comment]
bd45217 has been deployed to https://arxcis.github.io/flatstat to address what was discussed here. I am not sure if it solved this issue though. @tchx84 Do you have further concerns?

![image](https://user-images.githubusercontent.com/3092618/99859122-646b3f80-2b8f-11eb-8676-9174e2c3b89b.png)

**Comment by tchx84** [comment]
> [bd45217](https://github.com/Arxcis/flatstat/commit/bd4521789c7f5f5dc47ca6620f362eb763cac3db) has been deployed to https://arxcis.github.io/flatstat to address what was discussed here. I am not sure if it solved this issue though. @tchx84 Do you have further concerns?
> 
> ![image](https://user-images.githubusercontent.com/3092618/99859122-646b3f80-2b8f-11eb-8676-9174e2c3b89b.png)

maybe rename "talk-name" for "services", but I really think it would be better to remove it, and account these as simply holes :) but up to you.

Great work!

**Comment by Arxcis** [comment]
Sure, I will probably remove it eventually :+1:  I just feel like I have to get more familiar with `--talk-names` first. It is the thing I am least familiar with of all the holes in `Flatpak`.

`Flatseal` distinguishes between `Talks` or `Owns` and `System-bus` or  `Session-bus`, which is interesting. 
![image](https://user-images.githubusercontent.com/3092618/99862456-1d367c00-2b9a-11eb-881f-8e3f5ea7459a.png)

Is there any difference, in how serious the hole is, considering these 4 parameters? 
Is `owns` more serious than `talks`. Is `system-bus` more serious than `session-bus`?

I am assuming the `session-bus` and `system-bus` is not sandboxed, and evey app can see what every other app is doing. 

I assume the communication with a portal, on the other hand, is sandboxed, which makes the `portal-bus` different from `session-bus` and `system-bus`.

**Comment by Arxcis** [comment]
Based on `Flatseals` categorization, we could define and detect 4 new holes:

### 💥 Hole:  --talks-session-name
Your app has declared that it is talking to names on the session-bus, using one or more `--talk-name=NAME`

### 💥 Hole: --talks-system-name
Your app has declared that it is talking to names on the system-bus, using one or more `--system-talk-name=NAME`.

### 💥 Hole: --owns-session-name
Your app has declared that it owns a name on the session-bus, using one or more `--own-name=NAME`

### 💥 Hole:  --owns-system-name
Your app has declared that it owns a name on the system-bus, using one or more `--system-own-name=NAME`

**Comment by Arxcis** [comment]
With corresponding achievements:

### 🏅 Achievement: --no-name-talk
Your app does not talk to any names on the system- or session-bus. Your app is likely using portals.

### 🏅 Achievement: --no-name-own
Your app does not own any names on the system- or session-bus. Your app is likely using portals.

**Comment by tchx84** [comment]
There's one more tricky thing, accessing dbus services is not inherently bad (or good)... e.g. org.freedesktop.Notifications only means the app can send notifications, doesn't make less secure.

But, is not really possible to tell, by simply looking at the service name, whether accessing that service is "good" or "bad", it can be anything really. You could try to make a good/bad list, but it would be meant to be fail (as there will always be some service you don't account for).

**Comment by Arxcis** [comment]
But if I am using Signal messenger, and Signal sends a notification on `org.freedesktop.Notifications` telling me that I received a message from a friend. The notificaiton may even send parts of the message body. Could that notification in that case, leak messages to other applications, and compromise privacy?

**Comment by Arxcis** [comment]
It seems to me like using org.freedesktop.portal.Notification, is inherently better than using org.freedesktop.Notification - and should be encouraged. Am I right?

Why are so many apps using org.freedesktop.Notifications anyway? Shouldn't it be unecessary when you could use the portal instead?

**Comment by tchx84** [comment]
> It seems to me like using org.freedesktop.portal.Notification, is inherently better than using org.freedesktop.Notification - and should be encouraged. Am I right?
> 

Yes, but I don't that shouldn't be seen in manifests/metadata. Is supposed to be enable through some "portal dialog" during runtime.

> Why are so many apps using org.freedesktop.Notifications anyway? Shouldn't it be unecessary when you could use the portal instead?

Because is the standard (service) way of sending notifications in Linux desktop. And for a dev, is easier to just punch that hole, and changing their codes to use a portal.

**Comment by Arxcis** [comment]
Ok. Thank you. I think I understand now :smile: 

>And for a dev, is easier to just punch that hole 💥 , and changing their codes to use a portal.

Yes, of course. Hopefully it will become easier in the future, to not punch that hole :pray: But I think that If the dev wants to punch that hole, he should always be allowed to do that :muscle:  (unless the user :police_officer:  overrides him of course)
