### ISSUE TITLE
Detect if pipewire is enabled inside Flatpak

### ISSUE THREAD

**Issue by Arxcis** [Arxcis/flatstat#24]
**Hypothesis**
Detecting if wayland is enabled in a Flatpak is easy. We just check if we find the flag: 
```
--socket=wayland
```

As far as I know there is no `--socket=pipewire`-flag. Correct me if I am wrong 🙏

As far as I can tell from looking through `.json|.yaml`-files, pipewire-support can be detected if we find the flag:
```
--filesystem=xdg-run/pipewire-0
```
Example: https://github.com/flathub/org.musescore.MuseScore/blob/master/org.musescore.MuseScore.yaml#L34

**Questions**
- Is this the official way to enable the Pipwire-socket inside a Flatpak?
- @TheEvilSkeleton Can you confirm anything?
- Are there official documentation explaining this?
- Is there an equivalent to `--socket=fallback-x11` in the Pipewire world?

**Comment by TheEvilSkeleton** [comment]
Correct. There's no `--socket=pipewire` yet, and `--filesystem=xdg-run/pipewire-0` is in fact enabling PipeWire.

There's no fallback flag for PipeWire. If PipeWire doesn't exist, it will just use PulseAudio.

**Comment by Arxcis** [comment]
Thanks you for clarifying @TheEvilSkeleton 👏 

I did a test and detected **30** Pipewire-apps in the month **2021-05**:
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/3092618/121369707-5ec32480-c93c-11eb-83e0-c17273dbf1c7.png">



List of apps with Pipewire:
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/3092618/121368788-9ed5d780-c93b-11eb-8358-ecd0e5bb181d.png">
