### ISSUE TITLE
Rank by number of "holes" (permissions requested) instead of stars

### ISSUE THREAD

**Issue by tchx84** [Arxcis/flatstat#3]
Having a rank of apps based on how many permissions each one require, would be much more interesting.

**Comment by Arxcis** [comment]
Aha. Interesting. I imagine the first iteration would just count the number of `--finish-args`:

Example `Steam`  would get a value of **41** based on https://github.com/flathub/com.valvesoftware.Steam/blob/beta/com.valvesoftware.Steam.yml#L16-L60

Example `Signal` would get a value of **17** based on https://github.com/flathub/org.signal.Signal/blob/master/org.signal.Signal.json#L12-L29

@tchx84 was it something like this you had in mind?

**Comment by tchx84** [comment]
Quite similar! But I would only count permissions types once.

e.g.

```
  - --talk-name=org.freedesktop.ScreenSaver
  - --talk-name=org.freedesktop.PowerManagement
```

Would only add 1 point to the count. The max number of points would be the sum of every possible type of permission.

Otherwise the numbers can be a bit noisy.

**Comment by tchx84** [comment]
> Quite similar! But I would only count permissions types once.
> 
> e.g.
> 
> ```
>   - --talk-name=org.freedesktop.ScreenSaver
>   - --talk-name=org.freedesktop.PowerManagement
> ```
> 
> Would only add 1 point to the count. The max number of points would be the sum of every possible type of permission.
> 
> Otherwise the numbers can be a bit noisy.

You could also consider `--filesystem=home` and `--filesystem=all` different types (and same for `--socket` values, and so on).

What's interesting about this approach is that, later, you give different "weights" to each different permissions types, based on your own criteria.

**Comment by Arxcis** [comment]
Ok, based on your feedback, here is a plan:

## Plan

### Iteration 1 
The number of holes in the sandbox equals the number of `--finish-arg` entries in the `metafile`.

**Example**
```json
[
  "--filesystem=~/.config", 
  "--filesystem=~/.ssh", 
  "--filesystem=~/Games", 
  "--filesystem=host",
  "--talk-name=org.freedesktop.ScreenSaver",
  "--talk-name=org.freedesktop.PowerManagement"
]
```
**== 6 holes**

### Iteration 2
The number of holes in the sandbox equals the number of `--finish-arg`-types in the `metafile`. The list of `--finish-arg`-types is a curated list. Here is an example of 4 finish arg types:
```json
[
  "--filesystem=<any>", 
  "--filesytem=home", 
  "--filesystem=host",
  "--talk-name=<any>
]
```
**The example from iteration 1**
```json
[
  "--filesystem=~/.config", 
  "--filesystem=~/.ssh", 
  "--filesystem=~/Games", 
  "--filesystem=host",
  "--talk-name=org.freedesktop.ScreenSaver",
  "--talk-name=org.freedesktop.PowerManagement"
]
```
**== 3 holes**

### Iteration 3
The number of holes in the sandbox equals the number of `--finish-arg`-types in the `metafile`, times a curated multiplier, which size depends on how big we think the hole is:
```json
[
   "--filesystem=<any> x 1", 
   "--filesystem=home x 2", 
   "--filesystem=host x 3", 
   "--talk-name=<any> x 1", 
]`
```

**The example from iteration 1:**
```json
[
  "--filesystem=~/.config", 
  "--filesystem=~/.ssh", 
  "--filesystem=~/Games", 
  "--filesystem=host",
  "--talk-name=org.freedesktop.ScreenSaver",
  "--talk-name=org.freedesktop.PowerManagement"
]
```
**== 5 holes**

## Downsides to iteration 2 and 3

The downside I see to iteration 2 and 3, is that it is more difficult to explain to people. Iteration 1 is the simplest to explain.

**Comment by tchx84** [comment]
Right, iteration 2 would be great already.

**Comment by codewiz** [comment]
This proposal is reminiscent of EFF's "Who's Got Your Back" star ratings:
- https://www.eff.org/who-has-your-back-2017 (government data requests)
- https://www.eff.org/who-has-your-back-2018 (censorship)
- https://www.eff.org/wp/who-has-your-back-2019 (censorship again)

However, note how the EFF gives stars for good behavior rather than taking them away for bad behavior: positive reinforcement! :wink:

So maybe pick categories which are meaningful for users' privacy and security, such as:
 - Secure windowing and clipboard (Wayland with X11 fallback)
 - No direct access to personal files (no home filesystem)
 - Can't eavesdrop on microphone and camera

Perhaps this idea doesn't map too well to existing permissions... and perhaps users are already expecting to see a familiar list of permissions as in Android & iOS.

**Comment by tchx84** [comment]
> This proposal is reminiscent of EFF's "Who's Got Your Back" star ratings:
> 
> * https://www.eff.org/who-has-your-back-2017 (government data requests)
> * https://www.eff.org/who-has-your-back-2018 (censorship)
> * https://www.eff.org/wp/who-has-your-back-2019 (censorship again)
> 
> However, note how the EFF gives stars for good behavior rather than taking them away for bad behavior: positive reinforcement! 

This should be doable, since the number of "holes" is fixed, you can always do `max_holes - app_holes`, to invert.

> 
> So maybe pick categories which are meaningful for users' privacy and security, such as:
> 
> * Secure windowing and clipboard (Wayland with X11 fallback)
> * No direct access to personal files (no home filesystem)
> * Can't eavesdrop on microphone and camera
> 
> Perhaps this idea doesn't map too well to existing permissions... and perhaps users are already expecting to see a familiar list of permissions as in Android & iOS.

**Comment by tchx84** [comment]
@digitalethics you might be interested in this as well ;)

**Comment by Arxcis** [comment]
> However, note how the EFF gives stars for good behavior rather than taking them away for bad behavior: positive reinforcement! wink

@codewiz I fully agree with this approach. See my comment here https://github.com/tchx84/Flatseal/issues/163#issuecomment-726986120, which is the issue that inspired me to begin on https://github.com/Arxcis/flatstat 2 days ago :smile:

I really want `flatstat` to be a tool for encouraging the `flathub.org`-community :clap:, by showing stats about how things are **getting better**, instead of stats that show how bad everything is (bad example: https://flatkill.org/ :-1:  :-1:  :-1: )

**Comment by Arxcis** [comment]
OK. Since PR #10, we now store ALL `--finish-args` in [metafiles.json](https://github.com/Arxcis/flatstat/blob/master/db/flathub/metafiles.js), but I don't know what to do with it. I am gonna need some help here. Here are some real questions I need answers to.

The main question is: **Which entries in the the `--finish-arg`-list should be classified as a `hole` 💥 in the sandbox?**

**Exercise 1: How many `holes` does the latest `com.google.Chrome.yaml` have?**
```json
    {
      "ext": "yaml",
      "date": "2020-10-21T05:58:00Z",
      "finishArgs": {
        "device": [
          "all"
        ],
        "env": [
          "GTK_PATH"
        ],
        "filesystem": [
          "host-etc",
          "xdg-documents",
          "xdg-download",
          "xdg-music",
          "xdg-videos"
        ],
        "ownName": [
          "org.mpris.MediaPlayer2.chrome.*"
        ],
        "requireVersion": [
          "1.8.1"
        ],
        "share": [
          "ipc",
          "network"
        ],
        "socket": [
          "cups",
          "pulseaudio",
          "x11"
        ],
        "systemTalkName": [
          "org.freedesktop.Avahi"
        ],
        "talkName": [
          "org.freedesktop.FileManager1",
          "org.freedesktop.Notifications",
          "org.freedesktop.UPower",
          "org.freedesktop.secrets",
          "org.gnome.SessionManager"
        ]
      }
    },
```

**Exercise 2: How many `holes` does the latest `com.valvesoftware.Steam.yml` have?**
```json
      "ext": "yml",
      "date": "2020-10-05T12:51:20Z",
      "finishArgs": {
        "allow": [
          "bluetooth",
          "devel",
          "multiarch"
        ],
        "device": [
          "all"
        ],
        "env": [
          "ALSA_CONFIG_PATH",
          "DBUS_FATAL_WARNINGS",
          "LC_COLLATE",
          "LC_NUMERIC",
          "MESA_GLSL_CACHE_DIR",
          "PROTON_DEBUG_DIR",
          "SDL_VIDEODRIVER",
          "SSL_CERT_DIR",
          "STEAM_EXTRA_COMPAT_TOOLS_PATHS",
          "STEAM_RUNTIME",
          "STEAM_RUNTIME_PREFER_HOST_LIBRARIES",
          "TZ",
          "XDG_CONFIG_DIRS"
        ],
        "filesystem": [
          "xdg-music:ro",
          "xdg-pictures:ro",
          "xdg-run/app/com.discordapp.Discord:create"
        ],
        "persist": [
          "."
        ],
        "requireVersion": [
          "1.0.0"
        ],
        "share": [
          "ipc",
          "network"
        ],
        "socket": [
          "pulseaudio",
          "wayland",
          "x11"
        ],
        "systemTalkName": [
          "org.freedesktop.NetworkManager",
          "org.freedesktop.UPower"
        ],
        "talkName": [
          "org.freedesktop.Notifications",
          "org.freedesktop.PowerManagement",
          "org.freedesktop.ScreenSaver",
          "org.gnome.SettingsDaemon.MediaKeys",
          "org.kde.StatusNotifierWatcher"
        ]
      }
    },
```

**Comment by Arxcis** [comment]
**Bonus question**: Is it safe to assume there are no `holes` outside of `--finish-args`?

**Comment by Arxcis** [comment]
**Bonus question 2**: What is the value of `MAX_HOLES` ?

**Comment by Arxcis** [comment]
I have an idea. I will start out with a limited set of holes. Then the community can make suggestions about which holes we should add, remove, modify.

**Well-known holes**
- `--socket=x11`
- `--socket=pulseaudio`
- `--device=all`
- `--device=<other>`
- `--filesystem=home`
- `--filesystem=host`
- `--filesystem=<other>`

**MAX_HOLES = 7** per app

We use this list to calculate stats about how well individual apps are doing, and how well the entire Flathub ecosystem is doing, over time.

The dynamic version of this list will soon be available here https://arxcis.github.io/flatstat/about/

**Hole count**
- `com.valvesoftware.Steam.yml`: 4
- `com.google.Chrome.yaml`: 4

**Comment by Arxcis** [comment]
@tchx84 I got a PR #11 ready for review now, which may solve this issue. Please have a look at it :pray:
